// <auto-generated />
namespace HierarchyId.API.BreadthFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-alpha1")]
    public sealed partial class CompositeIndex : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CompositeIndex));
        
        string IMigrationMetadata.Id
        {
            get { return "201508262140575_CompositeIndex"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
